require("../../helpers/keys")

module.exports = {
  x1: [xxx],
  x2: [xxx, xxx],
  x3: [xxx, xxx, xxx],
  x4: [xxx, xxx, xxx, xxx],
  x5: [xxx, xxx, xxx, xxx, xxx],
  x6: [xxx, xxx, xxx, xxx, xxx, xxx],
  x7: [xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  x8: [xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  x9: [xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  x10: [xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  x11: [xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  x12: [xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx, xxx],
  _1: [___],
  _2: [___, ___],
  _3: [___, ___, ___],
  _4: [___, ___, ___, ___],
  _5: [___, ___, ___, ___, ___],
  _6: [___, ___, ___, ___, ___, ___],
  _7: [___, ___, ___, ___, ___, ___, ___],
  _8: [___, ___, ___, ___, ___, ___, ___, ___],
  _9: [___, ___, ___, ___, ___, ___, ___, ___, ___],
  _10: [___, ___, ___, ___, ___, ___, ___, ___, ___, ___],
  _11: [___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___],
  _12: [___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___, ___],
}
